/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.kototuz.ant;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int output=0x7f030000;
        public static final int prompt=0x7f030001;
    }
    public static final class layout {
        public static final int simple_layout=0x7f020000;
    }
}
